# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/kaggle_backpack_sales',
                'doc_host': 'https://ozpau.github.io',
                'git_url': 'https://github.com/ozpau/kaggle_backpack_sales',
                'lib_path': 'kaggle_backpack_sales'},
  'syms': {'kaggle_backpack_sales.core': {'kaggle_backpack_sales.core.foo': ('core.html#foo', 'kaggle_backpack_sales/core.py')}}}
